service: image-handler # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10

functions:
  index:
    handler: index.handler
    events:
      - http:
          path: /{any+}
          method: get
    environment:
      SOURCE_BUCKET: ${env:SOURCE_BUCKET}
      OBJECT_PREFIX: ${env:OBJECT_PREFIX}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
