service: image-handler

provider:
  name: aws
  runtime: nodejs8.10

functions:
  index:
    handler: index.handler
    events:
      - http:
          path: /{any+}
          method: get
    environment:
      SOURCE_BUCKET: ${env:SOURCE_BUCKET}
      OBJECT_PREFIX: ${env:OBJECT_PREFIX}
custom:
  serverless-offline:
    port: ${env:SERVERLESS_PORT}
plugins:
  - serverless-offline
  - serverless-dotenv-plugin
