org: ransom
app: image-handler-app
service: image-handler

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource: "arn:aws:s3:::${env:SOURCE_BUCKET}/${env:OBJECT_PREFIX}/*"

resources:
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Comment: Cloudfront distribution for serverless image handler
          DefaultCacheBehavior:
            TargetOriginId: ApiGateway
            ViewerProtocolPolicy: 'redirect-to-https'
            DefaultTTL: 30
            ForwardedValues:
              Headers:
                - 'Accept'
              QueryString: true
          Enabled: true
          Origins:
            - Id: ApiGateway
              DomainName:
                Fn::Join:
                  - "."
                  - - Ref: ApiGatewayRestApi
                    - execute-api.us-east-1.amazonaws.com
              OriginPath: /dev
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only

functions:
  index:
    handler: index.handler
    events:
      - http:
          path: /{any+}
          method: get
          contentHandling: CONVERT_TO_BINARY
    environment:
      SOURCE_BUCKET: ${env:SOURCE_BUCKET}
      SECURITY_KEY: ${env:SECURITY_KEY}
      OBJECT_PREFIX: ${env:OBJECT_PREFIX}
      REGION: us-east-1
custom:
  serverless-offline:
    port: ${env:SERVERLESS_PORT}
  apigwBinary:
    types:
      - '*/*'
plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-apigw-binary
  - serverless-apigwy-binary
